services:
  operator:
    privileged: true
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    attach: false
    environment:
      RUN_IN_KIOSK: ${RUN_IN_KIOSK:-false}
      RUN_IN_INCOGNITO: ${RUN_IN_INCOGNITO:-true}
      RUN_WITH_PROXY: ${RUN_WITH_PROXY:-false}
      PROXY_URL: ${PROXY_URL}
      #browser-use envs
      BROWSER_USE_OPENAI_API_KEY: ${BROWSER_USE_OPENAI_API_KEY}
      BROWSER_USE_ANTHROPIC_API_KEY: ${BROWSER_USE_ANTHROPIC_API_KEY}
      BROWSER_USE_WS_PORT: ${BROWSER_USE_WS_PORT:-8765}
      BROWSER_USE_WS_HOST: ${BROWSER_USE_WS_HOST:-0.0.0.0}
      BROWSER_USE_OPENAI_MODEL: ${BROWSER_USE_OPENAI_MODEL:-gpt-4o-mini} 
      BROWSER_USE_CDP_URL: ${BROWSER_USE_CDP_URL:-ws://localhost:9222}
      #encrypt-storage envs
      ENCRYPT_STORAGE_NILLION_ORG_SECRET_KEY: ${ENCRYPT_STORAGE_NILLION_ORG_SECRET_KEY}
      ENCRYPT_STORAGE_NILLION_ORG_DID: ${ENCRYPT_STORAGE_NILLION_ORG_DID}
      ENCRYPT_STORAGE_OPERATOR_PK: ${ENCRYPT_STORAGE_OPERATOR_PK}
      ENCRYPT_STORAGE_VAULT_ID: ${ENCRYPT_STORAGE_VAULT_ID}
      ENCRYPT_STORAGE_COPY_VAULT_ID: ${ENCRYPT_STORAGE_COPY_VAULT_ID}
      ENCRYPT_STORAGE_SCHEMA_ID: ${ENCRYPT_STORAGE_SCHEMA_ID}
      ENCRYPT_STORAGE_TASK_DATA_PATH: ${ENCRYPT_STORAGE_TASK_DATA_PATH}
      ENCRYPT_STORAGE_INTERVAL: ${ENCRYPT_STORAGE_INTERVAL}
      ENCRYPT_STORAGE_MONAD_RPC: ${ENCRYPT_STORAGE_MONAD_RPC}
      ENCRYPT_STORAGE_BROWMIA_DIAMOND_ADDRESS: ${ENCRYPT_STORAGE_BROWMIA_DIAMOND_ADDRESS}
    ports:
      - "127.0.0.1:5901:5901"
      - "127.0.0.1:8765:8765"
    restart: unless-stopped
    shm_size: '2g'
